const ar = {
  app: { name: 'AlgoTrainer', tagline: 'أتقن الخوارزميات، تحدي واحد في كل مرة' },
  nav: { home: 'الرئيسية', practice: 'تدريب', leaderboard: 'الترتيب', duels: 'مبارزات', profile: 'الملف' },
  home: { greeting: '!👋 {{name}} أهلاً', streak: '{{count}} يوم متتالي', xp: '{{count}} نقاط', level: 'المستوى {{level}}', dailyChallenge: 'تحدي اليوم', continueLearning: 'متابعة', learningPaths: 'مسارات', viewAll: 'عرض الكل', dashboard: 'لوحة التحكم', dashboardDesc: 'إحصائياتك المفصلة', visualizer: 'عارض الخوارزميات', visualizerDesc: 'شاهد خوارزميات الترتيب أثناء العمل' },
  paths: { beginner: 'خوارزميات المبتدئين', dataStructures: 'هياكل البيانات', advanced: 'خوارزميات متقدمة', interview: 'التحضير للمقابلات', beginnerDesc: 'ابدأ بالترتيب والبحث والأنماط الأساسية', dataStructuresDesc: 'أتقن المصفوفات والأشجار والرسوم البيانية', advancedDesc: 'البرمجة الديناميكية والخوارزميات الجشعة والمزيد', interviewDesc: 'أفضل المشاكل من مقابلات FAANG', lessons: '{{count}} دروس', progress: '{{percent}}% مكتمل' },
  practice: { title: 'تدريب', allProblems: 'الكل', easy: 'سهل', medium: 'متوسط', hard: 'صعب', solved: 'محلول', solve: 'حل', runCode: 'تشغيل', submit: 'إرسال', testCases: 'اختبارات', passed: 'نجح', failed: 'فشل', language: 'اللغة', searchPlaceholder: 'البحث عن مشاكل...', noProblems: 'لم يتم العثور على مشاكل', complete: '{{percent}}% مكتمل', problems: '{{count}} مشاكل', problem: '{{count}} مشكلة' },
  leaderboard: { title: 'الترتيب', global: 'عالمي', country: 'الدولة', friends: 'الأصدقاء', rank: 'المرتبة', weekly: 'الدوري الأسبوعي', noPlayers: 'لم يتم العثور على لاعبين', league: 'الدوري' },
  duels: { title: 'وضع المبارزة', findOpponent: 'البحث عن خصم', waiting: 'جاري البحث عن خصم...', vs: 'ضد', timeLeft: 'الوقت المتبقي', youWon: '!فزت 🏆', youLost: 'حظ أفضل في المرة القادمة!', draw: 'تعادل!', desc: 'تحدي مطور آخر لحل نفس المشكلة. الحل الصحيح الأسرع يفوز!', startDuel: 'بدء المبارزة', problem: 'المشكلة' },
  profile: { title: 'الملف الشخصي', solved: 'محلولة', rank: 'المرتبة', streak: 'السلسلة', achievements: 'الإنجازات', settings: 'الإعدادات', lowDataMode: 'وضع الاقتصاد', language: 'اللغة', theme: 'المظهر', colorTheme: 'مظهر اللون', downloadPacks: 'تحميل', offline: 'حزم بدون إنترنت', notifications: 'الإشعارات', logout: 'تسجيل الخروج', editProfile: 'تعديل الملف', displayName: 'الاسم', bio: 'نبذة', bioPlaceholder: 'صف نفسك في كلمات قليلة...', save: 'حفظ', saveError: 'خطأ في الحفظ', saveSuccess: 'تم تحديث الملف' },
  exercise: { aiCoach: 'مدرب ذكي', hint: 'تلميح', explanation: 'شرح', optimize: 'تحسين', complexity: 'التعقيد' },
  auth: { login: 'تسجيل الدخول', signup: 'إنشاء حساب', email: 'البريد الإلكتروني', password: 'كلمة المرور', google: 'المتابعة مع Google', apple: 'المتابعة مع Apple', github: 'المتابعة مع GitHub', or: 'أو' },
  badges: { firstSolve: 'أول حل', streak7: '7 أيام متتالية', streak30: '30 يوم متتالي', speedDemon: 'البرق', perfectWeek: 'أسبوع مثالي' },
  dashboard: { title: 'لوحة التحكم', totalTime: 'الوقت الكلي', successRate: 'معدل النجاح', exercisesSolved: 'التمارين المحلولة', totalXp: 'XP الكلي', inProgress: 'قيد التقدم', avgAttempts: 'المحاولات المتوسطة', streak: 'السلسلة', xpPerDay: 'XP يومياً (آخر 30 يوم)', solvedPerWeek: 'التمارين المحلولة أسبوعياً', byDifficulty: 'حسب الصعوبة', categoryProgress: 'التقدم حسب الفئة', noCategory: 'لا توجد فئات', languagesUsed: 'اللغات المستخدمة', easy: 'سهل', medium: 'متوسط', hard: 'صعب', solved: 'محلول' },
  forgotPassword: { title: 'نسيت كلمة المرور', desc: 'أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين', sendLink: 'إرسال الرابط', emailSent: 'تم إرسال بريد إلكتروني إلى', checkInbox: 'تحقق من صندوق الوارد.', backToLogin: 'العودة لتسجيل الدخول', sendError: 'خطأ في الإرسال', emailPlaceholder: 'عنوان بريدك الإلكتروني' },
  resetPassword: { title: 'كلمة مرور جديدة', desc: 'اختر كلمة مرور آمنة جديدة', newPassword: 'كلمة مرور جديدة', confirmPassword: 'تأكيد كلمة المرور', reset: 'إعادة تعيين', mismatch: 'كلمات المرور غير متطابقة', tooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل', success: 'تم تحديث كلمة المرور بنجاح!', error: 'خطأ في إعادة التعيين', invalidLink: 'هذا الرابط غير صالح أو منتهي الصلاحية.', backToLogin: 'العودة لتسجيل الدخول' },
  visualizer: { title: 'عارض الخوارزميات', newArray: 'مصفوفة جديدة', step: 'الخطوة {{current}}', total: '{{total}} إجمالي' },
  landing: { badge: 'تعلم وأنت تستمتع', heroTitle1: 'أتقن', heroTitle2: 'الخوارزميات', heroTitle3: '، تحدي واحد في كل مرة', heroDesc: 'المنصة المحفزة لتعلم هياكل البيانات والخوارزميات، مع تمارين تفاعلية ونظام تقدم محفز.', cta: 'ابدأ مجاناً', statsExercises: 'تمارين', statsPaths: 'مسارات', statsLeagues: 'دوريات', statsMotivation: 'حماس', featuresTitle: 'كل ما تحتاجه للتقدم', feature1Title: 'تعلم تدريجي', feature1Desc: 'مسارات منظمة من المبتدئ إلى الخبير', feature2Title: 'تمارين تفاعلية', feature2Desc: 'برمج مباشرة في المتصفح مع ردود فعل فورية', feature3Title: 'نظام الدوريات', feature3Desc: 'تقدم في الدوريات وتحدى متعلمين آخرين', feature4Title: 'مبارزات فورية', feature4Desc: 'تحدى أصدقاءك واصعد في الترتيب', feature5Title: 'تصور الخوارزميات', feature5Desc: 'افهم بصرياً كيف تعمل الخوارزميات', feature6Title: 'XP والسلاسل', feature6Desc: 'اكسب XP، حافظ على سلسلتك وارتقِ', howTitle: 'كيف يعمل؟', step1: 'سجل مجاناً واختر مسارك', step2: 'حل تمارين تفاعلية واكسب XP', step3: 'اصعد في الدوريات وتحدى متعلمين آخرين', ctaTitle: 'مستعد للبرمجة؟', ctaDesc: 'انضم لآلاف المتعلمين وابدأ رحلتك الخوارزمية.', ctaButton: 'هيا بنا!' },
  notFound: { title: '404', message: 'عذراً! الصفحة غير موجودة', backHome: 'العودة للرئيسية' },
  common: { loading: 'جاري التحميل...', error: 'حدث خطأ', onlyImages: 'يُقبل الصور فقط', imageTooLarge: 'الصورة كبيرة جداً (الحد 2 ميجا)', avatarUpdated: 'تم تحديث الصورة', uploadError: 'خطأ في الرفع' },
};

export default ar;
