const es = {
  app: { name: 'AlgoTrainer', tagline: 'Domina algoritmos, un desafío a la vez' },
  nav: { home: 'Inicio', practice: 'Práctica', leaderboard: 'Ranking', duels: 'Duelos', profile: 'Perfil' },
  home: { greeting: 'Hola, {{name}}! 👋', streak: '{{count}} días seguidos', xp: '{{count}} XP', level: 'Nivel {{level}}', dailyChallenge: 'Desafío diario', continueLearning: 'Continuar', learningPaths: 'Rutas', viewAll: 'Ver todo', dashboard: 'Panel de control', dashboardDesc: 'Tus estadísticas detalladas', visualizer: 'Visualizador de algoritmos', visualizerDesc: 'Observa los algoritmos de ordenamiento en acción' },
  paths: { beginner: 'Algoritmos básicos', dataStructures: 'Estructuras de datos', advanced: 'Algoritmos avanzados', interview: 'Prep. entrevistas', beginnerDesc: 'Comienza con ordenamiento y búsqueda', dataStructuresDesc: 'Arrays, árboles, grafos y hash maps', advancedDesc: 'Programación dinámica y más', interviewDesc: 'Top problemas de FAANG', lessons: '{{count}} lecciones', progress: '{{percent}}% completo' },
  practice: { title: 'Práctica', allProblems: 'Todos', easy: 'Fácil', medium: 'Medio', hard: 'Difícil', solved: 'Resuelto', solve: 'Resolver', runCode: 'Ejecutar', submit: 'Enviar', testCases: 'Pruebas', passed: 'Aprobado', failed: 'Fallido', language: 'Lenguaje', searchPlaceholder: 'Buscar problemas...', noProblems: 'No se encontraron problemas', complete: '{{percent}}% completo', problems: '{{count}} problemas', problem: '{{count}} problema' },
  leaderboard: { title: 'Ranking', global: 'Global', country: 'País', friends: 'Amigos', rank: 'Posición', weekly: 'Liga semanal', noPlayers: 'No se encontraron jugadores', league: 'Liga' },
  duels: { title: 'Modo Duelo', findOpponent: 'Buscar oponente', waiting: 'Buscando oponente...', vs: 'VS', timeLeft: 'Tiempo', youWon: '¡Ganaste! 🏆', youLost: '¡Más suerte la próxima!', draw: '¡Empate!', desc: 'Desafía a otro desarrollador con el mismo problema. ¡La solución correcta más rápida gana!', startDuel: 'Iniciar duelo', problem: 'Problema' },
  profile: { title: 'Perfil', solved: 'Resueltos', rank: 'Posición', streak: 'Racha', achievements: 'Logros', settings: 'Ajustes', lowDataMode: 'Modo ahorro', language: 'Idioma', theme: 'Tema', colorTheme: 'Tema de color', downloadPacks: 'Descargar', offline: 'Packs offline', notifications: 'Notificaciones', logout: 'Salir', editProfile: 'Editar perfil', displayName: 'Nombre', bio: 'Bio', bioPlaceholder: 'Descríbete en pocas palabras...', save: 'Guardar', saveError: 'Error al guardar', saveSuccess: 'Perfil actualizado' },
  exercise: { aiCoach: 'Coach IA', hint: 'Pista', explanation: 'Explicación', optimize: 'Optimización', complexity: 'Complejidad' },
  auth: { login: 'Iniciar sesión', signup: 'Registrarse', email: 'Email', password: 'Contraseña', google: 'Continuar con Google', apple: 'Continuar con Apple', github: 'Continuar con GitHub', or: 'o' },
  badges: { firstSolve: 'Primera solución', streak7: '7 días seguidos', streak30: '30 días seguidos', speedDemon: 'Velocista', perfectWeek: 'Semana perfecta' },
  dashboard: { title: 'Panel de control', totalTime: 'Tiempo total', successRate: 'Tasa de éxito', exercisesSolved: 'Ejercicios resueltos', totalXp: 'XP total', inProgress: 'En progreso', avgAttempts: 'Intentos prom.', streak: 'Racha', xpPerDay: 'XP por día (últimos 30 días)', solvedPerWeek: 'Ejercicios resueltos por semana', byDifficulty: 'Por dificultad', categoryProgress: 'Progreso por categoría', noCategory: 'Sin categorías disponibles', languagesUsed: 'Lenguajes usados', easy: 'Fácil', medium: 'Medio', hard: 'Difícil', solved: 'Resueltos' },
  forgotPassword: { title: 'Contraseña olvidada', desc: 'Introduce tu email para recibir un enlace de restablecimiento', sendLink: 'Enviar enlace', emailSent: 'Se ha enviado un email a', checkInbox: 'Revisa tu bandeja de entrada.', backToLogin: 'Volver al inicio de sesión', sendError: 'Error al enviar', emailPlaceholder: 'Tu dirección de email' },
  resetPassword: { title: 'Nueva contraseña', desc: 'Elige una nueva contraseña segura', newPassword: 'Nueva contraseña', confirmPassword: 'Confirmar contraseña', reset: 'Restablecer contraseña', mismatch: 'Las contraseñas no coinciden', tooShort: 'La contraseña debe tener al menos 6 caracteres', success: '¡Contraseña actualizada!', error: 'Error al restablecer', invalidLink: 'Este enlace no es válido o ha expirado.', backToLogin: 'Volver al inicio de sesión' },
  visualizer: { title: 'Visualizador de algoritmos', newArray: 'Nuevo array', step: 'Paso {{current}}', total: '{{total}} en total' },
  landing: { badge: 'Aprende divirtiéndote', heroTitle1: 'Domina los', heroTitle2: 'algoritmos', heroTitle3: ', un desafío a la vez', heroDesc: 'La plataforma gamificada para aprender estructuras de datos y algoritmos, con ejercicios interactivos y un sistema de progresión motivador.', cta: 'Empezar gratis', statsExercises: 'Ejercicios', statsPaths: 'Rutas', statsLeagues: 'Ligas', statsMotivation: 'Motivación', featuresTitle: 'Todo lo que necesitas para progresar', feature1Title: 'Aprendizaje progresivo', feature1Desc: 'Rutas estructuradas de principiante a experto', feature2Title: 'Ejercicios interactivos', feature2Desc: 'Codifica directamente en el navegador con feedback instantáneo', feature3Title: 'Sistema de ligas', feature3Desc: 'Progresa en las ligas y desafía a otros aprendices', feature4Title: 'Duelos en tiempo real', feature4Desc: 'Desafía a tus amigos y sube en el ranking', feature5Title: 'Visualización de algoritmos', feature5Desc: 'Comprende visualmente cómo funcionan los algoritmos', feature6Title: 'XP y Rachas', feature6Desc: 'Gana XP, mantén tu racha y sube de nivel', howTitle: '¿Cómo funciona?', step1: 'Regístrate gratis y elige tu ruta', step2: 'Resuelve ejercicios interactivos y gana XP', step3: 'Sube en las ligas y desafía a otros aprendices', ctaTitle: '¿Listo para codificar?', ctaDesc: 'Únete a miles de aprendices y comienza tu viaje algorítmico.', ctaButton: '¡Vamos!' },
  notFound: { title: '404', message: '¡Ups! Página no encontrada', backHome: 'Volver al inicio' },
  common: { loading: 'Cargando...', error: 'Ocurrió un error', onlyImages: 'Solo se aceptan imágenes', imageTooLarge: 'Imagen demasiado grande (máx 2 MB)', avatarUpdated: 'Avatar actualizado', uploadError: 'Error al subir' },
};

export default es;
