const ha = {
  app: { name: 'AlgoTrainer', tagline: 'Koyi algorithms, kalubale daya a lokaci daya' },
  nav: { home: 'Gida', practice: 'Aiki', leaderboard: 'Matsayi', duels: 'Gasar', profile: 'Bayani' },
  home: { greeting: 'Sannu, {{name}}! 👋', streak: 'Kwanaki {{count}} a jere', xp: '{{count}} XP', level: 'Mataki {{level}}', dailyChallenge: 'Kalubalen yau', continueLearning: 'Ci gaba', learningPaths: 'Hanyoyi', viewAll: 'Duba duka', dashboard: 'Dashibodi', dashboardDesc: 'Bayanan kididdiga na ka', visualizer: 'Mai nuna algorithm', visualizerDesc: 'Kalli algorithms na tsari suna aiki' },
  paths: { beginner: 'Algorithms na farko', dataStructures: 'Tsarin bayanai', advanced: 'Algorithms na ci gaba', interview: 'Shirye-shiryen hira', beginnerDesc: 'Fara da tsari, nema da tsarin farko', dataStructuresDesc: 'Koyi arrays, bishiyoyi, graphs da hash maps', advancedDesc: 'Shirye-shiryen motsi, algorithms na kwadayi da kari', interviewDesc: 'Manyan matsaloli daga FAANG', lessons: 'Darasi {{count}}', progress: '{{percent}}% ya kammala' },
  practice: { title: 'Aiki', allProblems: 'Duka', easy: 'Sauƙi', medium: 'Matsakaici', hard: 'Wuya', solved: 'An warware', solve: 'Warware', runCode: 'Gudanar', submit: 'Aika', testCases: 'Gwaji', passed: 'Ya wuce', failed: 'Ya gaza', language: 'Harshe', searchPlaceholder: 'Nemo matsaloli...', noProblems: 'Ba a sami matsaloli ba', complete: '{{percent}}% ya kammala', problems: 'Matsaloli {{count}}', problem: 'Matsala {{count}}' },
  leaderboard: { title: 'Matsayi', global: 'Duniya', country: 'Ƙasa', friends: 'Abokai', rank: 'Matsayi', weekly: 'Gasar mako', noPlayers: 'Ba a sami yan wasa ba', league: 'Gasar' },
  duels: { title: 'Yanayin Gasar', findOpponent: 'Nemo abokin gasa', waiting: 'Ana neman abokin gasa...', vs: 'DA', timeLeft: 'Lokaci ya rage', youWon: 'Ka ci nasara! 🏆', youLost: 'Sa\'a a gaba!', draw: 'Daidai!', desc: 'Kalubanci wani mai gina shirye-shirye don warware matsala ɗaya. Amsar da ta fi sauri da ta dace ta ci nasara!', startDuel: 'Fara gasar', problem: 'Matsala' },
  profile: { title: 'Bayani', solved: 'An warware', rank: 'Matsayi', streak: 'Jere', achievements: 'Nasarori', settings: 'Saituna', lowDataMode: 'Yanayin tattalin kudi', language: 'Harshe', theme: 'Jigo', colorTheme: 'Jigon launi', downloadPacks: 'Sauke', offline: 'Fakitin ciki', notifications: 'Sanarwa', logout: 'Fita', editProfile: 'Gyara bayani', displayName: 'Suna', bio: 'Bayani', bioPlaceholder: 'Bayyana kanka a kalmomi kaɗan...', save: 'Ajiye', saveError: 'Kuskure wajen ajiyewa', saveSuccess: 'An sabunta bayani' },
  exercise: { aiCoach: 'Koci na AI', hint: 'Alama', explanation: 'Bayani', optimize: 'Ingantawa', complexity: 'Rikitarwa' },
  auth: { login: 'Shiga', signup: 'Yi rajista', email: 'Imel', password: 'Kalmar sirri', google: 'Ci gaba da Google', apple: 'Ci gaba da Apple', github: 'Ci gaba da GitHub', or: 'ko' },
  badges: { firstSolve: 'Warware na farko', streak7: 'Kwanaki 7 a jere', streak30: 'Kwanaki 30 a jere', speedDemon: 'Sauri', perfectWeek: 'Mako cikakke' },
  dashboard: { title: 'Dashibodi', totalTime: 'Jimlar lokaci', successRate: 'Adadin nasara', exercisesSolved: 'Ayyukan da aka warware', totalXp: 'Jimlar XP', inProgress: 'Ana ci gaba', avgAttempts: 'Matsakaicin yunƙuri', streak: 'Jere', xpPerDay: 'XP a kowace rana (kwanaki 30 da suka wuce)', solvedPerWeek: 'Ayyuka a kowace mako', byDifficulty: 'Ta hanyar wahala', categoryProgress: 'Ci gaba ta bangare', noCategory: 'Babu bangare', languagesUsed: 'Harsunan da aka yi amfani', easy: 'Sauƙi', medium: 'Matsakaici', hard: 'Wuya', solved: 'An warware' },
  forgotPassword: { title: 'An manta kalmar sirri', desc: 'Shigar da imel ɗinka don samun hanyar sake saita', sendLink: 'Aika hanya', emailSent: 'An aika imel zuwa', checkInbox: 'Duba akwatin saƙo naka.', backToLogin: 'Koma shiga', sendError: 'Kuskure wajen aikawa', emailPlaceholder: 'Adireshin imel ɗinka' },
  resetPassword: { title: 'Sabuwar kalmar sirri', desc: 'Zaɓi sabuwar kalmar sirri mai aminci', newPassword: 'Sabuwar kalmar sirri', confirmPassword: 'Tabbatar da kalmar sirri', reset: 'Sake saita', mismatch: 'Kalmomin sirri ba su dace ba', tooShort: 'Kalmar sirri dole ta kasance haruffa 6 ko fiye', success: 'An sabunta kalmar sirri!', error: 'Kuskure wajen sake saita', invalidLink: 'Wannan hanyar ba ta aiki ko ta ƙare.', backToLogin: 'Koma shiga' },
  visualizer: { title: 'Mai nuna algorithm', newArray: 'Sabon array', step: 'Mataki {{current}}', total: '{{total}} duka' },
  landing: { badge: 'Koyi kana jin daɗi', heroTitle1: 'Koyi', heroTitle2: 'algorithms', heroTitle3: ', kalubale daya a lokaci daya', heroDesc: 'Dandalin wasa don koyon tsarin bayanai da algorithms, tare da ayyukan hulɗa da tsarin ci gaba mai ƙarfafawa.', cta: 'Fara kyauta', statsExercises: 'Ayyuka', statsPaths: 'Hanyoyi', statsLeagues: 'Gasanni', statsMotivation: 'Ƙarfafawa', featuresTitle: 'Duk abin da kake bukata don ci gaba', feature1Title: 'Koyon sannu-sannu', feature1Desc: 'Hanyoyi masu tsari daga farko zuwa ƙwarewa', feature2Title: 'Ayyukan hulɗa', feature2Desc: 'Rubuta code a cikin burauza kai tsaye', feature3Title: 'Tsarin gasar', feature3Desc: 'Ci gaba a cikin gasanni ka kuma kalubanci wasu', feature4Title: 'Gasannin lokaci na ainihi', feature4Desc: 'Kalubanci abokanka ka kuma hau matsayi', feature5Title: 'Nunin algorithm', feature5Desc: 'Fahimci yadda algorithms ke aiki ta ido', feature6Title: 'XP da Jere', feature6Desc: 'Sami XP, kiyaye jere kuma hau mataki', howTitle: 'Yaya yake aiki?', step1: 'Yi rajista kyauta ka zaɓi hanyarka', step2: 'Warware ayyukan hulɗa ka sami XP', step3: 'Hau mataki a cikin gasanni ka kuma kalubanci wasu', ctaTitle: 'Kana shirye don rubuta code?', ctaDesc: 'Haɗa kai da dubban dalibai ka fara tafiyar algorithm ɗinka.', ctaButton: 'Bari mu tafi!' },
  notFound: { title: '404', message: 'Yi haƙuri! Ba a sami shafin ba', backHome: 'Koma gida' },
  common: { loading: 'Ana lodi...', error: 'Kuskure ya faru', onlyImages: 'Hotuna kaɗai ake ɗauka', imageTooLarge: 'Hoton ya yi girma (max 2 MB)', avatarUpdated: 'An sabunta hoton', uploadError: 'Kuskure wajen lodi' },
};

export default ha;
