const ln = {
  app: { name: 'AlgoTrainer', tagline: 'Yekola algorithme, défi moko na mbala moko' },
  nav: { home: 'Ndako', practice: 'Mosala', leaderboard: 'Bokeli', duels: 'Etumba', profile: 'Profil' },
  home: { greeting: 'Mbote, {{name}}! 👋', streak: 'Mikolo {{count}} na nsima', xp: '{{count}} XP', level: 'Eteni {{level}}', dailyChallenge: 'Défi ya mokolo', continueLearning: 'Kokoba', learningPaths: 'Nzela', viewAll: 'Tala nyonso', dashboard: 'Dashibodi', dashboardDesc: 'Bastatistique na yo ya mozindo', visualizer: 'Kimonisi ya algorithme', visualizerDesc: 'Tala algorithme ya kotia na mosala' },
  paths: { beginner: 'Algorithme ya ebandeli', dataStructures: 'Bokeli ya ba données', advanced: 'Algorithme ya likolo', interview: 'Bolengeli ya entretien', beginnerDesc: 'Banda na kotia, koluka mpe ba modèle ya ebandeli', dataStructuresDesc: 'Yekola arrays, nzete, graphe mpe hash maps', advancedDesc: 'Programme dynamique, algorithme ya lokoso mpe mingi', interviewDesc: 'Ba problème ya likolo ya FAANG', lessons: 'Mateya {{count}}', progress: '{{percent}}% esili' },
  practice: { title: 'Mosala', allProblems: 'Nyonso', easy: 'Pétéé', medium: 'Katikati', hard: 'Makasi', solved: 'Esilisami', solve: 'Silisa', runCode: 'Kokimisa', submit: 'Kotinda', testCases: 'Bameki', passed: 'Eleki', failed: 'Elongi te', language: 'Monoko', searchPlaceholder: 'Luka ba problème...', noProblems: 'Ba problème ezali te', complete: '{{percent}}% esili', problems: 'Ba problème {{count}}', problem: 'Problème {{count}}' },
  leaderboard: { title: 'Bokeli', global: 'Mokili', country: 'Ekolo', friends: 'Baninga', rank: 'Esika', weekly: 'Ligue ya poso', noPlayers: 'Basani ezali te', league: 'Ligue' },
  duels: { title: 'Etumba', findOpponent: 'Luka motɛmɛli', waiting: 'Tozali koluka motɛmɛli...', vs: 'CONTRE', timeLeft: 'Ntango etikali', youWon: 'Olongi! 🏆', youLost: 'Esengo mbala ya nsima!', draw: 'Egalité!', desc: 'Benga mosali mosusu ya code mpo na kosilisa problème moko. Eyano ya malamu ya noki eleki elongi!', startDuel: 'Banda etumba', problem: 'Problème' },
  profile: { title: 'Profil', solved: 'Esilisami', rank: 'Esika', streak: 'Nsima', achievements: 'Bilongi', settings: 'Bopesi', lowDataMode: 'Mode ya kobomba', language: 'Monoko', theme: 'Elilingi', colorTheme: 'Elilingi ya langi', downloadPacks: 'Kokitisa', offline: 'Ba paquet ya libanda', notifications: 'Bayebisi', logout: 'Kobima', editProfile: 'Kobongola profil', displayName: 'Nkombo', bio: 'Biographie', bioPlaceholder: 'Milobela na maloba moke...', save: 'Kobomba', saveError: 'Libunga ya kobomba', saveSuccess: 'Profil ebongolamaki' },
  exercise: { aiCoach: 'Entraîneur AI', hint: 'Elembo', explanation: 'Ndimbola', optimize: 'Kobongisa', complexity: 'Mozindo' },
  auth: { login: 'Kokota', signup: 'Komikoma', email: 'Email', password: 'Liloba ya nkuku', google: 'Kokoba na Google', apple: 'Kokoba na Apple', github: 'Kokoba na GitHub', or: 'to' },
  badges: { firstSolve: 'Bosilisi ya liboso', streak7: 'Mikolo 7 na nsima', streak30: 'Mikolo 30 na nsima', speedDemon: 'Noki', perfectWeek: 'Poso ya kokoka' },
  dashboard: { title: 'Dashibodi', totalTime: 'Ntango nyonso', successRate: 'Taux ya bolongi', exercisesSolved: 'Misala esilisami', totalXp: 'XP nyonso', inProgress: 'Ezali kokende', avgAttempts: 'Bomeki ya katikati', streak: 'Nsima', xpPerDay: 'XP na mokolo (mikolo 30 ya nsima)', solvedPerWeek: 'Misala na poso', byDifficulty: 'Na mozindo', categoryProgress: 'Maendeleo na catégorie', noCategory: 'Catégorie ezali te', languagesUsed: 'Minoko esalelamaki', easy: 'Pétéé', medium: 'Katikati', hard: 'Makasi', solved: 'Esilisami' },
  forgotPassword: { title: 'Obosani liloba ya nkuku', desc: 'Koma email na yo mpo ozwa lien ya kobongola', sendLink: 'Tinda lien', emailSent: 'Email etindamaki na', checkInbox: 'Tala boîte na yo.', backToLogin: 'Kozonga na bokoti', sendError: 'Libunga ya kotinda', emailPlaceholder: 'Adresse email na yo' },
  resetPassword: { title: 'Liloba ya nkuku ya sika', desc: 'Pona liloba ya nkuku ya sika ya kobatela', newPassword: 'Liloba ya nkuku ya sika', confirmPassword: 'Kondimisa liloba ya nkuku', reset: 'Kobongola', mismatch: 'Ba liloba ya nkuku ekokani te', tooShort: 'Liloba ya nkuku esengeli kozala na ba caractère 6 to koleka', success: 'Liloba ya nkuku ebongolamaki!', error: 'Libunga ya kobongola', invalidLink: 'Lien oyo ezali malamu te to esilaki.', backToLogin: 'Kozonga na bokoti' },
  visualizer: { title: 'Kimonisi ya algorithme', newArray: 'Array ya sika', step: 'Eteni {{current}}', total: '{{total}} nyonso' },
  landing: { badge: 'Yekola na esengo', heroTitle1: 'Yekola', heroTitle2: 'algorithme', heroTitle3: ', défi moko na mbala moko', heroDesc: 'Plateforme ya masano mpo na koyekola bokeli ya ba données mpe algorithme, na misala ya interactif mpe système ya maendeleo oyo epesaka motema.', cta: 'Banda ofele', statsExercises: 'Misala', statsPaths: 'Nzela', statsLeagues: 'Ba ligue', statsMotivation: 'Motema', featuresTitle: 'Nyonso oyo osengeli na yango mpo na kokende liboso', feature1Title: 'Boyekoli ya moke moke', feature1Desc: 'Nzela oyo ebongisami banda ebandeli tii na moto ya mayele', feature2Title: 'Misala ya interactif', feature2Desc: 'Koma code mbala moko na navigateur na réponse ya noki', feature3Title: 'Système ya ba ligue', feature3Desc: 'Kende liboso na ba ligue mpe benga bayekoli mosusu', feature4Title: 'Bitumba ya ntango ya solo', feature4Desc: 'Benga baninga na yo mpe mata na bokeli', feature5Title: 'Kimonisi ya algorithme', feature5Desc: 'Sosola na miso ndenge algorithme esalaka', feature6Title: 'XP mpe Nsima', feature6Desc: 'Zwa XP, batela nsima na yo mpe mata na eteni', howTitle: 'Esalaka ndenge nini?', step1: 'Komikoma ofele mpe pona nzela na yo', step2: 'Silisa misala ya interactif mpe zwa XP', step3: 'Mata na ba ligue mpe benga bayekoli mosusu', ctaTitle: 'Osilá mpo na kokoma code?', ctaDesc: 'Sanga na bankóto ya bayekoli mpe banda mobembo na yo ya algorithme.', ctaButton: 'Tókende!' },
  notFound: { title: '404', message: 'Limbisa! Lokasa emonani te', backHome: 'Kozonga na ndako' },
  common: { loading: 'Ezali kokota...', error: 'Libunga esalemi', onlyImages: 'Kaka bililingi nde bandimami', imageTooLarge: 'Elilingi eleki monene (max 2 MB)', avatarUpdated: 'Elilingi ebongolamaki', uploadError: 'Libunga ya kotia' },
};

export default ln;
