const pt = {
  app: { name: 'AlgoTrainer', tagline: 'Domine algoritmos, um desafio de cada vez' },
  nav: { home: 'Início', practice: 'Prática', leaderboard: 'Ranking', duels: 'Duelos', profile: 'Perfil' },
  home: { greeting: 'Olá, {{name}}! 👋', streak: '{{count}} dias seguidos', xp: '{{count}} XP', level: 'Nível {{level}}', dailyChallenge: 'Desafio diário', continueLearning: 'Continuar', learningPaths: 'Trilhas', viewAll: 'Ver tudo', dashboard: 'Painel', dashboardDesc: 'Suas estatísticas detalhadas', visualizer: 'Visualizador de algoritmos', visualizerDesc: 'Assista os algoritmos de ordenação em ação' },
  paths: { beginner: 'Algoritmos básicos', dataStructures: 'Estruturas de dados', advanced: 'Algoritmos avançados', interview: 'Prep. entrevistas', beginnerDesc: 'Comece com ordenação, busca e padrões básicos', dataStructuresDesc: 'Domine arrays, árvores, grafos e hash maps', advancedDesc: 'Programação dinâmica, algoritmos gulosos e mais', interviewDesc: 'Top problemas de entrevistas FAANG', lessons: '{{count}} lições', progress: '{{percent}}% completo' },
  practice: { title: 'Prática', allProblems: 'Todos', easy: 'Fácil', medium: 'Médio', hard: 'Difícil', solved: 'Resolvido', solve: 'Resolver', runCode: 'Executar', submit: 'Enviar', testCases: 'Testes', passed: 'Aprovado', failed: 'Falhou', language: 'Linguagem', searchPlaceholder: 'Buscar problemas...', noProblems: 'Nenhum problema encontrado', complete: '{{percent}}% completo', problems: '{{count}} problemas', problem: '{{count}} problema' },
  leaderboard: { title: 'Ranking', global: 'Global', country: 'País', friends: 'Amigos', rank: 'Posição', weekly: 'Liga semanal', noPlayers: 'Nenhum jogador encontrado', league: 'Liga' },
  duels: { title: 'Modo Duelo', findOpponent: 'Buscar oponente', waiting: 'Buscando oponente...', vs: 'VS', timeLeft: 'Tempo', youWon: 'Você venceu! 🏆', youLost: 'Mais sorte na próxima!', draw: 'Empate!', desc: 'Desafie outro desenvolvedor no mesmo problema. A solução correta mais rápida vence!', startDuel: 'Iniciar duelo', problem: 'Problema' },
  profile: { title: 'Perfil', solved: 'Resolvidos', rank: 'Posição', streak: 'Sequência', achievements: 'Conquistas', settings: 'Configurações', lowDataMode: 'Modo economia', language: 'Idioma', theme: 'Tema', colorTheme: 'Tema de cor', downloadPacks: 'Baixar', offline: 'Packs offline', notifications: 'Notificações', logout: 'Sair', editProfile: 'Editar perfil', displayName: 'Nome', bio: 'Bio', bioPlaceholder: 'Descreva-se em poucas palavras...', save: 'Salvar', saveError: 'Erro ao salvar', saveSuccess: 'Perfil atualizado' },
  exercise: { aiCoach: 'Coach IA', hint: 'Dica', explanation: 'Explicação', optimize: 'Otimização', complexity: 'Complexidade' },
  auth: { login: 'Entrar', signup: 'Cadastrar', email: 'Email', password: 'Senha', google: 'Continuar com Google', apple: 'Continuar com Apple', github: 'Continuar com GitHub', or: 'ou' },
  badges: { firstSolve: 'Primeira solução', streak7: '7 dias seguidos', streak30: '30 dias seguidos', speedDemon: 'Velocista', perfectWeek: 'Semana perfeita' },
  dashboard: { title: 'Painel', totalTime: 'Tempo total', successRate: 'Taxa de sucesso', exercisesSolved: 'Exercícios resolvidos', totalXp: 'XP total', inProgress: 'Em progresso', avgAttempts: 'Tentativas méd.', streak: 'Sequência', xpPerDay: 'XP por dia (últimos 30 dias)', solvedPerWeek: 'Exercícios resolvidos por semana', byDifficulty: 'Por dificuldade', categoryProgress: 'Progresso por categoria', noCategory: 'Sem categorias disponíveis', languagesUsed: 'Linguagens usadas', easy: 'Fácil', medium: 'Médio', hard: 'Difícil', solved: 'Resolvidos' },
  forgotPassword: { title: 'Esqueceu a senha', desc: 'Digite seu email para receber um link de redefinição', sendLink: 'Enviar link', emailSent: 'Um email foi enviado para', checkInbox: 'Verifique sua caixa de entrada.', backToLogin: 'Voltar ao login', sendError: 'Erro ao enviar', emailPlaceholder: 'Seu endereço de email' },
  resetPassword: { title: 'Nova senha', desc: 'Escolha uma nova senha segura', newPassword: 'Nova senha', confirmPassword: 'Confirmar senha', reset: 'Redefinir senha', mismatch: 'As senhas não coincidem', tooShort: 'A senha deve ter pelo menos 6 caracteres', success: 'Senha atualizada com sucesso!', error: 'Erro ao redefinir', invalidLink: 'Este link não é válido ou expirou.', backToLogin: 'Voltar ao login' },
  visualizer: { title: 'Visualizador de algoritmos', newArray: 'Novo array', step: 'Passo {{current}}', total: '{{total}} no total' },
  landing: { badge: 'Aprenda se divertindo', heroTitle1: 'Domine os', heroTitle2: 'algoritmos', heroTitle3: ', um desafio de cada vez', heroDesc: 'A plataforma gamificada para aprender estruturas de dados e algoritmos, com exercícios interativos e um sistema de progressão motivador.', cta: 'Começar grátis', statsExercises: 'Exercícios', statsPaths: 'Trilhas', statsLeagues: 'Ligas', statsMotivation: 'Motivação', featuresTitle: 'Tudo que você precisa para progredir', feature1Title: 'Aprendizado progressivo', feature1Desc: 'Trilhas estruturadas de iniciante a especialista', feature2Title: 'Exercícios interativos', feature2Desc: 'Code diretamente no navegador com feedback instantâneo', feature3Title: 'Sistema de ligas', feature3Desc: 'Progrida nas ligas e desafie outros aprendizes', feature4Title: 'Duelos em tempo real', feature4Desc: 'Desafie seus amigos e suba no ranking', feature5Title: 'Visualização de algoritmos', feature5Desc: 'Entenda visualmente como os algoritmos funcionam', feature6Title: 'XP e Sequências', feature6Desc: 'Ganhe XP, mantenha sua sequência e suba de nível', howTitle: 'Como funciona?', step1: 'Cadastre-se grátis e escolha sua trilha', step2: 'Resolva exercícios interativos e ganhe XP', step3: 'Suba nas ligas e desafie outros aprendizes', ctaTitle: 'Pronto para programar?', ctaDesc: 'Junte-se a milhares de aprendizes e comece sua jornada algorítmica.', ctaButton: 'Vamos lá!' },
  notFound: { title: '404', message: 'Ops! Página não encontrada', backHome: 'Voltar ao início' },
  common: { loading: 'Carregando...', error: 'Ocorreu um erro', onlyImages: 'Apenas imagens são aceitas', imageTooLarge: 'Imagem muito grande (máx 2 MB)', avatarUpdated: 'Avatar atualizado', uploadError: 'Erro ao enviar' },
};

export default pt;
