const sw = {
  app: { name: 'AlgoTrainer', tagline: 'Boresha algorithimu, changamoto moja kwa wakati' },
  nav: { home: 'Nyumbani', practice: 'Mazoezi', leaderboard: 'Nafasi', duels: 'Mashindano', profile: 'Wasifu' },
  home: { greeting: 'Habari, {{name}}! 👋', streak: 'Siku {{count}} mfululizo', xp: '{{count}} XP', level: 'Kiwango {{level}}', dailyChallenge: 'Changamoto ya leo', continueLearning: 'Endelea', learningPaths: 'Njia', viewAll: 'Angalia zote', dashboard: 'Dashibodi', dashboardDesc: 'Takwimu zako za kina', visualizer: 'Kionyesho cha algorithimu', visualizerDesc: 'Tazama algorithimu za kupanga zikifanya kazi' },
  paths: { beginner: 'Algorithimu za mwanzo', dataStructures: 'Muundo wa data', advanced: 'Algorithimu za juu', interview: 'Maandalizi ya mahojiano', beginnerDesc: 'Anza na kupanga, kutafuta na mifumo ya msingi', dataStructuresDesc: 'Boresha arrays, miti, grafu na hash maps', advancedDesc: 'Programu ya nguvu, algorithimu za tamaa na zaidi', interviewDesc: 'Matatizo bora kutoka FAANG', lessons: 'Masomo {{count}}', progress: '{{percent}}% imekamilika' },
  practice: { title: 'Mazoezi', allProblems: 'Yote', easy: 'Rahisi', medium: 'Wastani', hard: 'Ngumu', solved: 'Imetatuliwa', solve: 'Tatua', runCode: 'Endesha', submit: 'Wasilisha', testCases: 'Majaribio', passed: 'Imepita', failed: 'Imeshindwa', language: 'Lugha', searchPlaceholder: 'Tafuta matatizo...', noProblems: 'Hakuna matatizo yaliyopatikana', complete: '{{percent}}% imekamilika', problems: 'Matatizo {{count}}', problem: 'Tatizo {{count}}' },
  leaderboard: { title: 'Nafasi', global: 'Ulimwengu', country: 'Nchi', friends: 'Marafiki', rank: 'Nafasi', weekly: 'Ligi ya wiki', noPlayers: 'Hakuna wachezaji waliopatikana', league: 'Ligi' },
  duels: { title: 'Hali ya Mashindano', findOpponent: 'Tafuta mpinzani', waiting: 'Inatafuta mpinzani...', vs: 'DHIDI', timeLeft: 'Muda uliobaki', youWon: 'Umeshinda! 🏆', youLost: 'Bahati njema ijayo!', draw: 'Sare!', desc: 'Changamsha mtengenezaji mwingine kutatua tatizo lile lile. Suluhisho sahihi la haraka linashinda!', startDuel: 'Anza mashindano', problem: 'Tatizo' },
  profile: { title: 'Wasifu', solved: 'Imetatuliwa', rank: 'Nafasi', streak: 'Mfululizo', achievements: 'Mafanikio', settings: 'Mipangilio', lowDataMode: 'Hali ya kuokoa', language: 'Lugha', theme: 'Mandhari', colorTheme: 'Mandhari ya rangi', downloadPacks: 'Pakua', offline: 'Pakiti za nje ya mtandao', notifications: 'Arifa', logout: 'Ondoka', editProfile: 'Hariri wasifu', displayName: 'Jina', bio: 'Maelezo', bioPlaceholder: 'Jieleze kwa maneno machache...', save: 'Hifadhi', saveError: 'Hitilafu ya kuhifadhi', saveSuccess: 'Wasifu umesasishwa' },
  exercise: { aiCoach: 'Kocha wa AI', hint: 'Dokezo', explanation: 'Maelezo', optimize: 'Uboreshaji', complexity: 'Ugumu' },
  auth: { login: 'Ingia', signup: 'Jisajili', email: 'Barua pepe', password: 'Nenosiri', google: 'Endelea na Google', apple: 'Endelea na Apple', github: 'Endelea na GitHub', or: 'au' },
  badges: { firstSolve: 'Suluhisho la kwanza', streak7: 'Siku 7 mfululizo', streak30: 'Siku 30 mfululizo', speedDemon: 'Kasi', perfectWeek: 'Wiki kamili' },
  dashboard: { title: 'Dashibodi', totalTime: 'Muda wote', successRate: 'Kiwango cha mafanikio', exercisesSolved: 'Mazoezi yaliyotatuliwa', totalXp: 'XP jumla', inProgress: 'Inaendelea', avgAttempts: 'Majaribio wastani', streak: 'Mfululizo', xpPerDay: 'XP kwa siku (siku 30 zilizopita)', solvedPerWeek: 'Mazoezi kwa wiki', byDifficulty: 'Kwa ugumu', categoryProgress: 'Maendeleo kwa kategoria', noCategory: 'Hakuna kategoria', languagesUsed: 'Lugha zilizotumika', easy: 'Rahisi', medium: 'Wastani', hard: 'Ngumu', solved: 'Imetatuliwa' },
  forgotPassword: { title: 'Umesahau nenosiri', desc: 'Ingiza barua pepe yako kupokea kiungo cha kuweka upya', sendLink: 'Tuma kiungo', emailSent: 'Barua pepe imetumwa kwa', checkInbox: 'Angalia sanduku lako.', backToLogin: 'Rudi kwenye kuingia', sendError: 'Hitilafu ya kutuma', emailPlaceholder: 'Anwani yako ya barua pepe' },
  resetPassword: { title: 'Nenosiri jipya', desc: 'Chagua nenosiri jipya salama', newPassword: 'Nenosiri jipya', confirmPassword: 'Thibitisha nenosiri', reset: 'Weka upya', mismatch: 'Nenosiri hazifanani', tooShort: 'Nenosiri lazima liwe na herufi 6 au zaidi', success: 'Nenosiri limesasishwa!', error: 'Hitilafu ya kuweka upya', invalidLink: 'Kiungo hiki si halali au kimekwisha.', backToLogin: 'Rudi kwenye kuingia' },
  visualizer: { title: 'Kionyesho cha algorithimu', newArray: 'Array mpya', step: 'Hatua {{current}}', total: '{{total}} jumla' },
  landing: { badge: 'Jifunze ukifurahia', heroTitle1: 'Boresha', heroTitle2: 'algorithimu', heroTitle3: ', changamoto moja kwa wakati', heroDesc: 'Jukwaa la mchezo la kujifunza muundo wa data na algorithimu, na mazoezi ya maingiliano na mfumo wa maendeleo unaomotisha.', cta: 'Anza bure', statsExercises: 'Mazoezi', statsPaths: 'Njia', statsLeagues: 'Ligi', statsMotivation: 'Hamasa', featuresTitle: 'Kila kitu unachohitaji kuendelea', feature1Title: 'Kujifunza hatua kwa hatua', feature1Desc: 'Njia zilizopangwa kutoka mwanzo hadi mtaalam', feature2Title: 'Mazoezi ya maingiliano', feature2Desc: 'Programu moja kwa moja kwenye kivinjari', feature3Title: 'Mfumo wa ligi', feature3Desc: 'Endelea katika ligi na changamsha wanafunzi wengine', feature4Title: 'Mashindano ya wakati halisi', feature4Desc: 'Changamsha marafiki zako na panda nafasi', feature5Title: 'Taswira ya algorithimu', feature5Desc: 'Elewa kwa macho jinsi algorithimu zinavyofanya kazi', feature6Title: 'XP na Mfululizo', feature6Desc: 'Pata XP, dumisha mfululizo wako na panda kiwango', howTitle: 'Inafanyaje kazi?', step1: 'Jisajili bure na uchague njia yako', step2: 'Tatua mazoezi ya maingiliano na upate XP', step3: 'Panda katika ligi na changamsha wanafunzi wengine', ctaTitle: 'Uko tayari kuprogramu?', ctaDesc: 'Jiunge na maelfu ya wanafunzi na uanze safari yako ya algorithimu.', ctaButton: 'Twende!' },
  notFound: { title: '404', message: 'Samahani! Ukurasa haujapatikana', backHome: 'Rudi nyumbani' },
  common: { loading: 'Inapakia...', error: 'Hitilafu imetokea', onlyImages: 'Picha tu zinakubaliwa', imageTooLarge: 'Picha kubwa sana (max 2 MB)', avatarUpdated: 'Picha imesasishwa', uploadError: 'Hitilafu ya kupakia' },
};

export default sw;
