const yo = {
  app: { name: 'AlgoTrainer', tagline: 'Kọ algorithm, ipenija kan ni akoko kan' },
  nav: { home: 'Ilé', practice: 'Àdàṣe', leaderboard: 'Ipò', duels: 'Ìdíje', profile: 'Profaili' },
  home: { greeting: 'Bawo, {{name}}! 👋', streak: 'Ọjọ́ {{count}} léraléra', xp: '{{count}} XP', level: 'Ìpele {{level}}', dailyChallenge: 'Ipenija ọjọ́', continueLearning: 'Tẹ̀síwájú', learningPaths: 'Ọ̀nà', viewAll: 'Wo gbogbo', dashboard: 'Dashibọọdu', dashboardDesc: 'Àwọn ìṣirò rẹ alaye', visualizer: 'Afihan algorithm', visualizerDesc: 'Wo àwọn algorithm tito lẹsẹsẹ nṣiṣẹ́' },
  paths: { beginner: 'Algorithm àkọ́kọ́', dataStructures: 'Ètò data', advanced: 'Algorithm gíga', interview: 'Ìmúrasílẹ̀ ìfọ̀rọ̀wánilẹ́nuwò', beginnerDesc: 'Bẹ̀rẹ̀ pẹ̀lú tito, wíwá àti àwọn àpẹẹrẹ ìpìlẹ̀', dataStructuresDesc: 'Kọ́ arrays, igi, àwọn graphs àti hash maps', advancedDesc: 'Ètò agbára, algorithm ojúkokoro àti díẹ̀ sí i', interviewDesc: 'Àwọn ìṣòro tó ga jùlọ láti FAANG', lessons: 'Ẹ̀kọ́ {{count}}', progress: '{{percent}}% ti parí' },
  practice: { title: 'Àdàṣe', allProblems: 'Gbogbo', easy: 'Rọrùn', medium: 'Àárín', hard: 'Líle', solved: 'Ti yanjú', solve: 'Yanjú', runCode: 'Ṣiṣẹ́', submit: 'Fi ránṣẹ́', testCases: 'Àdánwò', passed: 'Kọjá', failed: 'Kùnà', language: 'Èdè', searchPlaceholder: 'Wá ìṣòro...', noProblems: 'Kò sí ìṣòro', complete: '{{percent}}% ti parí', problems: 'Ìṣòro {{count}}', problem: 'Ìṣòro {{count}}' },
  leaderboard: { title: 'Ipò', global: 'Àgbáyé', country: 'Orílẹ̀-èdè', friends: 'Ọ̀rẹ́', rank: 'Ipò', weekly: 'Ẹgbẹ́ ọ̀sẹ̀', noPlayers: 'Kò sí aṣeré', league: 'Ẹgbẹ́' },
  duels: { title: 'Ìdíje', findOpponent: 'Wá alatako', waiting: 'Ń wá alatako...', vs: 'LÒDÌ SÍ', timeLeft: 'Àkókò tó kù', youWon: 'O ṣẹ́gun! 🏆', youLost: 'Oríire ní ìgbà tó ń bọ̀!', draw: 'Dọ́gba!', desc: 'Pe olùgbékalẹ̀ mìíràn láti yanjú ìṣòro kan náà. Ojútùú tó yára jùlọ tó tọ̀nà ni ó borí!', startDuel: 'Bẹ̀rẹ̀ ìdíje', problem: 'Ìṣòro' },
  profile: { title: 'Profaili', solved: 'Ti yanjú', rank: 'Ipò', streak: 'Léraléra', achievements: 'Àṣeyọrí', settings: 'Ètò', lowDataMode: 'Ètò ìfipamọ́', language: 'Èdè', theme: 'Àwòrán', colorTheme: 'Àwòrán àwọ̀', downloadPacks: 'Gbà', offline: 'Àpò àìsí ayélujára', notifications: 'Ìfitónilétí', logout: 'Jáde', editProfile: 'Ṣàtúnṣe profaili', displayName: 'Orúkọ', bio: 'Àlàyé', bioPlaceholder: 'Ṣàpèjúwe ara rẹ ní ọ̀rọ̀ díẹ̀...', save: 'Fi pamọ́', saveError: 'Àṣìṣe nínú fífi pamọ́', saveSuccess: 'Profaili ti ṣàtúnṣe' },
  exercise: { aiCoach: 'Olùkọ́ AI', hint: 'Àmì', explanation: 'Àlàyé', optimize: 'Ìlọsíwájú', complexity: 'Ìdíjú' },
  auth: { login: 'Wọlé', signup: 'Forúkọsílẹ̀', email: 'Ímeèlì', password: 'Ọ̀rọ̀ aṣínà', google: 'Tẹ̀síwájú pẹ̀lú Google', apple: 'Tẹ̀síwájú pẹ̀lú Apple', github: 'Tẹ̀síwájú pẹ̀lú GitHub', or: 'tàbí' },
  badges: { firstSolve: 'Ojútùú àkọ́kọ́', streak7: 'Ọjọ́ 7 léraléra', streak30: 'Ọjọ́ 30 léraléra', speedDemon: 'Ìyára', perfectWeek: 'Ọ̀sẹ̀ pípé' },
  dashboard: { title: 'Dashibọọdu', totalTime: 'Àkókò lápapọ̀', successRate: 'Ìwọ̀n àṣeyọrí', exercisesSolved: 'Àdàṣe tí a yanjú', totalXp: 'XP lápapọ̀', inProgress: 'Ń ṣiṣẹ́ lọ́wọ́', avgAttempts: 'Ìgbìyànjú àárín', streak: 'Léraléra', xpPerDay: 'XP lójoojúmọ́ (ọjọ́ 30 tó kọjá)', solvedPerWeek: 'Àdàṣe lọ́ṣọ̀ọ̀ṣẹ̀', byDifficulty: 'Gẹ́gẹ́ bí ìṣòro', categoryProgress: 'Ìlọsíwájú gẹ́gẹ́ bí ẹ̀ka', noCategory: 'Kò sí ẹ̀ka', languagesUsed: 'Èdè tí a lò', easy: 'Rọrùn', medium: 'Àárín', hard: 'Líle', solved: 'Ti yanjú' },
  forgotPassword: { title: 'Ọ̀rọ̀ aṣínà tí a gbàgbé', desc: 'Tẹ ímeèlì rẹ láti gba ọ̀nà àtúnṣe', sendLink: 'Fi ọ̀nà ránṣẹ́', emailSent: 'Ímeèlì ti ránṣẹ́ sí', checkInbox: 'Ṣàyẹ̀wò àpótí rẹ.', backToLogin: 'Padà sí ìwọlé', sendError: 'Àṣìṣe nínú fífi ránṣẹ́', emailPlaceholder: 'Àdírẹ́sì ímeèlì rẹ' },
  resetPassword: { title: 'Ọ̀rọ̀ aṣínà tuntun', desc: 'Yan ọ̀rọ̀ aṣínà tuntun tó láàbò', newPassword: 'Ọ̀rọ̀ aṣínà tuntun', confirmPassword: 'Jẹ́rísí ọ̀rọ̀ aṣínà', reset: 'Tún ṣe', mismatch: 'Àwọn ọ̀rọ̀ aṣínà kò bára mu', tooShort: 'Ọ̀rọ̀ aṣínà gbọ́dọ̀ ní lẹ́tà 6 ó kéré jùlọ', success: 'Ọ̀rọ̀ aṣínà ti ṣàtúnṣe!', error: 'Àṣìṣe nínú àtúnṣe', invalidLink: 'Ọ̀nà yìí kò tọ̀nà tàbí ti parẹ́.', backToLogin: 'Padà sí ìwọlé' },
  visualizer: { title: 'Afihan algorithm', newArray: 'Array tuntun', step: 'Ìgbésẹ̀ {{current}}', total: '{{total}} lápapọ̀' },
  landing: { badge: 'Kọ́ nígbà tí o ń gbádùn', heroTitle1: 'Kọ́', heroTitle2: 'algorithm', heroTitle3: ', ìpenijà kan ní àkókò kan', heroDesc: 'Pẹpẹ eré láti kọ́ ètò data àti algorithm, pẹ̀lú àdàṣe alátagbà àti ètò ìtẹ̀síwájú tó ń fún ní ìmísí.', cta: 'Bẹ̀rẹ̀ lọ́fẹ̀ẹ́', statsExercises: 'Àdàṣe', statsPaths: 'Ọ̀nà', statsLeagues: 'Ẹgbẹ́', statsMotivation: 'Ìmísí', featuresTitle: 'Gbogbo ohun tí o nílò láti tẹ̀síwájú', feature1Title: 'Ẹ̀kọ́ díẹ̀díẹ̀', feature1Desc: 'Ọ̀nà tí a ṣètò láti àkọ́kọ́ sí amọ̀ye', feature2Title: 'Àdàṣe alátagbà', feature2Desc: 'Kóòdù tààrà nínú búráwúsà pẹ̀lú èsì lẹ́sẹ̀kẹsẹ̀', feature3Title: 'Ètò ẹgbẹ́', feature3Desc: 'Tẹ̀síwájú nínú àwọn ẹgbẹ́ kí o sì pe àwọn akẹ́kọ̀ọ́ mìíràn', feature4Title: 'Ìdíje àkókò gidi', feature4Desc: 'Pe àwọn ọ̀rẹ́ rẹ kí o sì gun ipò', feature5Title: 'Àfihàn algorithm', feature5Desc: 'Lóye bí àwọn algorithm ṣe ń ṣiṣẹ́ ní ojú', feature6Title: 'XP àti Léraléra', feature6Desc: 'Gba XP, mú léraléra rẹ dúró kí o sì gun ìpele', howTitle: 'Báwo ni ó ṣe ń ṣiṣẹ́?', step1: 'Forúkọsílẹ̀ lọ́fẹ̀ẹ́ kí o sì yan ọ̀nà rẹ', step2: 'Yanjú àdàṣe alátagbà kí o sì gba XP', step3: 'Gun ìpele nínú àwọn ẹgbẹ́ kí o sì pe àwọn akẹ́kọ̀ọ́ mìíràn', ctaTitle: 'Ṣé o ṣetán láti kọ̀ọ̀dù?', ctaDesc: 'Darapọ̀ mọ́ ẹgbẹẹgbẹ̀rún akẹ́kọ̀ọ́ kí o sì bẹ̀rẹ̀ ìrìnàjò algorithm rẹ.', ctaButton: 'Jẹ́ ká lọ!' },
  notFound: { title: '404', message: 'Ojú-ìwé kò rí!', backHome: 'Padà sí ilé' },
  common: { loading: 'Ó ń gbé...', error: 'Àṣìṣe kan wáyé', onlyImages: 'Àwòrán nìkan ni a gba', imageTooLarge: 'Àwòrán tóbi jù (max 2 MB)', avatarUpdated: 'Àwòrán ti ṣàtúnṣe', uploadError: 'Àṣìṣe nínú ìgbékalẹ̀' },
};

export default yo;
